# Generated by Django 6.0.2 on 2026-02-16 09:27

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_reminde_6ad23d_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Task deadline (user sets this)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When was the last reminder sent', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_reminder_time',
            field=models.DateTimeField(blank=True, help_text='Next calculated reminder time (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_level',
            field=models.CharField(choices=[('daily', 'Daily (5+ days left)'), ('half_day', 'Half-day (2-5 days left)'), ('quarter_day', 'Quarter-day (1-2 days left)'), ('urgent', 'Urgent (< 1 day left)'), ('final', 'Final (< 2 hours left)'), ('overdue', 'Overdue')], default='daily', help_text='Current reminder intensity level', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['next_reminder_time'], name='tasks_next_re_1e8c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_deadlin_7f16a6_idx'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_time',
        ),
    ]
