# Generated by Django 6.0.2 on 2026-02-16 09:27

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
